# Generated by Django 4.2.7 on 2023-11-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(related_name='tag', through='articles.Scope', to='articles.article'),
        ),
    ]
