# Generated by Django 4.2.7 on 2023-11-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_tag_title_articletag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
