# Generated by Django 4.2.7 on 2023-11-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_articletag_tag_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Тематика статьи')),
                ('maine', models.BooleanField(verbose_name='Основной')),
            ],
        ),
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
