# Generated by Django 4.2.7 on 2023-11-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_tag_options_article_tags_alter_tag_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='is_main',
            field=models.BooleanField(null=True, verbose_name='Основной'),
        ),
    ]
