# Generated by Django 4.2.7 on 2023-11-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_article_scopes_tag_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='article_scopes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
