# Generated by Django 4.2.7 on 2023-11-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_scopes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='article_scopes',
        ),
    ]
