# Generated by Django 4.2.7 on 2023-11-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_studentteachers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentTeachers',
        ),
    ]
