# Generated by Django 4.2.7 on 2023-11-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_alter_measurement_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='sensor',
            new_name='sensor_id',
        ),
    ]
